spring:
  application:
    name: teacher
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:55001}
    virtual-host: ${RABBITMQ_VHOST:/}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 2
          max-interval: 10s
          multiplier: 2

server:
  port: ${PORT:50005}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:50001/eureka/}

logging:
  level:
    root: INFO

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 30000
        loggerLevel: ${FEIGN_LOG_LEVEL:NONE}